Repository Exerra/karen-bot-docs, pull requests merged in 2021-07, with the labels that each got.

#6 Improve whatToWorkOn.md
  development/whatToWorkOn.md
  index.html
Labels: development guide, documentation

#8 Fixed issues brought by sider
  README.md
  _coverpage.md
Labels: documentation

#9 Added "Labeler" GH action
  .github/labeler-pr.yml
  .github/workflows/label-pr.yml
Labels: enhancement

#11 Command section in guide
  _sidebar.md
  index.html
  users/commands.md
Labels: documentation, enhancement

#12 Removed a horrible sorting implementation in commands.md
  users/commands.md
Labels: bug, documentation

#14 Merges gitbook documentation
  _sidebar.md
  api.json
  index.html
  users/settings.md
  users/supportedCrypto.md
  users/swearWords.md
Labels: documentation

#18 Improve coverpage
  _404.md
  _coverpage.md
  index.html
Labels: documentation, enhancement

#19 Added trademarks and link to settings
  README.md
  index.html
Labels: documentation, enhancement

#21 Fixed typo in word customizable
  users/swearWords.md
Labels: documentation, good first issue
